-- Create the 'awards' table
create table if not exists public.awards (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('ronda_inicial', 'partido_final')),
  title text not null,
  player_name text,
  team_name text,
  description text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Prevent duplicate awards in the same category (e.g., only one MVP per final)
  -- This is critical for the parser to update existing records instead of creating duplicates
  unique (category, title)
);

-- Enable Row Level Security (RLS) to secure the data
alter table public.awards enable row level security;

-- Policy 1: Everyone can READ awards
create policy "Enable read access for all users"
on public.awards for select
using (true);

-- Policy 2: Only Authenticated Users (Admins) can INSERT/UPDATE/DELETE
-- (Adjusting this to 'authenticated' allows your admin login to work via the app)
create policy "Enable write access for authenticated users only"
on public.awards for all
using (auth.role() = 'authenticated');
